name: hot_restart_timeline
description: A webserver which automatically reloads the timelines of spot on code changes
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  dartx: ^1.1.0
  path: ^1.9.0
  server_nano: ^1.5.1

dev_dependencies:
  lint: ^2.3.0
  spot:
    path: ../
  test: ^1.24.0
