// ignore_for_file: require_trailing_commas

import 'package:checks/checks.dart';
import 'package:flutter/material.dart';
import 'package:spot/spot.dart';

/// Matchers for [CircularProgressIndicator] auto-generated by spot
///
/// ```dart
/// spot<CircularProgressIndicator>().printMatchers();
/// ```
extension CircularProgressIndicatorMatcher on WidgetMatcher<CircularProgressIndicator> {

  WidgetMatcher<CircularProgressIndicator> hasValueWhere(MatchProp<double> match) {
    return hasProp<double>('value', match);
  }
  
  WidgetMatcher<CircularProgressIndicator> hasValue(double value) {
    return hasProp<double>('value', (it) => it.equals(value));
  }

}

extension CircularProgressIndicatorSelector on WidgetSelector<CircularProgressIndicator> {
  WidgetSelector<CircularProgressIndicator> withValueMatching(MatchProp<double> match) {
    return withProp<double>('value', match);
  }
  
  WidgetSelector<CircularProgressIndicator> withValue(double value) {
    return withProp<double>('value', (it) => it.equals(value));
  }

}
    
    