// ignore_for_file: require_trailing_commas

import 'package:checks/checks.dart';
import 'package:flutter/material.dart';
import 'package:spot/spot.dart';

/// Matchers for [LinearProgressIndicator] auto-generated by spot
///
/// ```dart
/// spot<LinearProgressIndicator>().printMatchers();
/// ```
extension LinearProgressIndicatorMatcher on WidgetMatcher<LinearProgressIndicator> {
  WidgetMatcher<LinearProgressIndicator> hasValueWhere(MatchProp<double?> match) {
    return hasProp<double?>('value', match);
  }
  
  WidgetMatcher<LinearProgressIndicator> hasValue(double? value) {
    return hasProp<double?>('value', (it) => it.equals(value));
  }

}

extension LinearProgressIndicatorSelector on WidgetSelector<LinearProgressIndicator> {
  WidgetSelector<LinearProgressIndicator> withValueMatching(MatchProp<double?> match) {
    return withProp<double?>('value', match);
  }
  
  WidgetSelector<LinearProgressIndicator> withValue(double? value) {
    return withProp<double?>('value', (it) => it.equals(value));
  }

}
    
    