name: counter_app
description: "Spot sample project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  spot:
    path: ../
