name: Nightly

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  nightly:
    timeout-minutes: 10
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        version: [ "stable", "beta", "master" ]

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.version }}
      - run: flutter pub get
      - run: flutter test
